hosts:
  mysql.scielo.org:
    ssh_user: rundeck
    services:
      mariadb: mariadb
    proxmox:
      node: mysql.scielo.org
      vmid: 157

  node01-submission.scielo.org:
    ssh_user: rundeck
    services:
      apache: httpd
      mariadb: mariadb
    http_healthcheck: "https://preprints.scielo.org/"
    proxmox:
      node: node01-submission.scielo.org
      vmid: 124
