hosts:
  db-node-01.example.local:
    ssh_user: rundeck
    services:
      mariadb: mariadb
    proxmox:
      node: nodeXX
      vmid: 123

  app-node-01.example.local:
    ssh_user: rundeck
    services:
      apache: httpd
      mariadb: mariadb
    http_healthcheck: "https://app-node-01.example.local/"
    proxmox:
      node: nodeYY
      vmid: 456
